export * from './Film';
export * from './People';
export * from './Planet';
export * from './Species';
export * from './Starship';
export * from './Vehicle';
export * from './ResourceType.enum';
export * from './PagedResults';
export * from './SearchResult';
